site:
  title: Elixir Full-Stack
  url: https://elixircl.github.io/elixir-fullstack
  start_page: "ROOT::index.adoc"

content:
  sources:
    - url: .
      branches: HEAD
      start_path: .

antora:
  extensions:
    - require: "@antora/lunr-extension"

asciidoc:
  extensions:
    - asciidoctor-emoji
    - asciidoctor-kroki
  attributes:
    kroki-fetch-diagram: true
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
    highlightjs-theme: monokai
    highlightjs-languages: js, elixir, sql, yaml, html, css, php

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # https://gitlab.com/antora/antora-ui-default/-/tree/master/src/partials
  supplemental_files: supplemental-ui/

output:
  dir: docs/
