defmodule StoicQuotes.Repo.Migrations.AddUniqueQuoteIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quotes, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :quote, :text, null: false
      add :author, :text, null: false
      add :source, :text, null: false
    end

    create unique_index(:quotes, [:quote], name: "quotes_unique_quote_index")
  end

  def down do
    drop_if_exists unique_index(:quotes, [:quote], name: "quotes_unique_quote_index")

    drop table(:quotes)
  end
end
